Mailing list name
eduardoboucas/staticman pull request #391
Opened 2020-10-24 16:58 UTC by hispanic

Addresses issue #127 - "Mailgun mailing lists - give each one a name"

I added support for passing in a new "parentName" option to the "entry" endpoint. You can set it to whatever value you prefer. For example: 
  - options[parentName] = Post "Staticman is Awesome"
  - options[parentName] = Post staticman-is-awesome
  - options[parentName] = Comment 88688c70-12d1-11eb-b135-db5a5177adbc
  - options[parentName] = Comment 88688c70-12d1-11eb-b135-db5a5177adbc on Post staticman-is-awesome
  - options[parentName] = Blog "Mike's Tech Thoughts"

I chose "parentName" intentionally, as I believe @eduardoboucas originally added the "parent" option as "a unique identifier to the entry the user is subscribing to." More info: https://github.com/eduardoboucas/staticman/issues/42#issuecomment-262938831

When supplied, this value will be used to populate the "name" property of the created mailing list in Mailgun. In addition, supplying this option will also trigger the population of the "description" property for the mailing list. The description will be of the following form: 
  - "Subscribers to: [parentName] ([repo-username]/[repo-name])

I have chosen to deliberately expose the relevant repository in the description, as that is factored into the creation of the mailing list ID.

If a "parentName" option is not passed, the mailing list will be created without a name or description, just as currently implemented.

As part of this change, I have modified the mailing list creation logic to set two other properties exposed by the Mailgun API:
  - Set "access_level" to "readonly". This will only allow authenticated users to post to the list. This is the Mailgun default, but I think it wise to explicitly set it in case the default changes.
  - Set "reply_preference" to "sender". Restricting replies to "sender" (as opposed to all members of the list) would seem to be the safest and most appropriate option for a list meant to receive notifications.

By setting the "reply_preference" property on the Mailgun mailing list to "sender", the "reply-to" of every email sent via the mailing list will be postmaster@[mailgun domain] instead of the "from" address (e.g., noreply@staticman.net). I defeat this by explicitly setting the "h:Reply-To" header (to be the same as the "from" address).

As part of this commit, I created a SubscriptionsManager.test.js, which did not exist.

If/when merged-in, I'll be happy to submit a PR to update the documentation site.

Thank you for Staticman!

2020-11-03 14:39 UTC, hispanic commented
Seems like "parent" should get in here somehow. I modified the code to, instead, populate the mailing list description as follows:

- Subscribers to [parent] ([repo-username]/[repo-name])

2020-11-24 02:11 UTC, alexwaibel requested changes
@hisanic I made a few small suggestions

2020-11-24 02:11 UTC, alexwaibel commented on lib/Notification.js
> +    payload['h:Reply-To'] = payload.from
``` suggestion
const from = from: `Staticman <${config.get('email.fromAddress')}>`
const payload = {
  from,
  to,
  subject,
  html: this._buildMessage(fields, options, data),
  'h:Reply-To': from
}
```
nit: can set reply header in payload directly.

2020-11-24 02:11 UTC, alexwaibel commented on lib/SubscriptionsManager.js
> +          let payload = {
```suggestion
          let newMailingListConfig = {
```
This name would be more descriptive

2020-11-24 02:11 UTC, alexwaibel commented on lib/SubscriptionsManager.js
> +              ' (' + this.parameters.username + '/' + this.parameters.repository + ')'
```suggestion
          payload.access_level = 'readonly'
          payload.reply_preference = 'sender'

          const entryName = options.parentName
          if (entryName) {
            payload.name = entryName
            payload.description = `Subscribers to ${entryId} (${this.parameters.username}/${this.parameters.repository})`
```

nit: Can use fstring for description instead of string concatenation here

2020-11-24 02:11 UTC, alexwaibel commented on lib/SubscriptionsManager.js
>      })
I don't think catching and rejecting the error does anything here but I could be wrong.

2020-11-25 19:57 UTC, hispanic commented
Thanks, Alex. I see I've got other notifications, too. I'll look into everything in more detail once I get past Thanksgiving and related activities.

2020-12-05 17:38 UTC, closed without merging

2020-12-05 20:28 UTC, hispanic commented
Stepping away from this effort in light of the codebase refactor that is underway. More info in https://github.com/eduardoboucas/staticman/pull/396#issuecomment-739404099. Thanks.