ReCAPTCHA support implemented.
eduardoboucas/staticman pull request #67
Opened 2016-12-29 00:15 UTC by zburgermeiszter

2016-12-29 00:15 UTC, zburgermeiszter commented
Closes: https://github.com/eduardoboucas/staticman/issues/20

2017-02-16 23:36 UTC, zburgermeiszter commented
PR updated. @eduardoboucas 
PR submitted against `master` as your `dev` branch is far behind master.

2017-02-19 22:25 UTC, eduardoboucas commented
Sorry for the delay, @zburgermeiszter, and thanks for your PR! I'll review this in the next couple of days.

2017-02-19 23:23 UTC, zburgermeiszter commented
That's great.
It the current state the CAPTCHA enforcement is driven by the server and can not be configured uniquely for API consumers (blogs).

Also, for extra security it could compare the received ReCAPTCHA API details to the branch of the website where it has been submitted.
It is not possible to hijack the CAPTCHA currently, but possible to replace ReCAPTCHA API credentials to a more loosely configured one. Needs investigation if it's a real risk.

Both of these would add extra delay to the somment submission response time.

2017-02-24 00:09 UTC, eduardoboucas requested changes

2017-02-24 00:09 UTC, eduardoboucas commented on .env
> +FOO=BAR
Surely you meant to delete this? 😄

2017-02-24 00:09 UTC, eduardoboucas commented on config.js
> +  reCAPTCHA: {
I know this is the right way to write it, but I'd prefer to keep config properties `camelCased`. Would you mind changing that?

2017-02-24 00:09 UTC, eduardoboucas commented on controllers/process.js
> +let staticman;
The codebase is following [StandardJS](http://standardjs.com/), which doesn't use semi-colons. Could you change that, please?

2017-02-24 00:09 UTC, eduardoboucas commented on docker-compose.yml
> +      RSA_PRIVATE_KEY: |
Did you mean to commit a private key?

2017-02-24 00:09 UTC, eduardoboucas commented on index.js
> -    res.locals.apiVersion = req.params.version
Why did you delete this?

2017-02-24 00:13 UTC, eduardoboucas commented
Thanks for this! I've added some comments.

Also, to make sure I fully understand what's going on, could you answer these:

- How would people (end users) install this? Do they need to create an account with a third-party? If so, which one?
- What code do they need to include in their forms for this to work?
- Could you briefly describe the flow of data using reCAPTCHA and how it differs from the current implementation? (e.g. data goes through this function, which makes a request to X, which writes result to Y)
- Are there any breaking changes?

2017-02-25 12:30 UTC, zburgermeiszter commented on .env
> +FOO=BAR
That's an example for people who want to use the `.env` file, but might be better simply mention it in the readme.

2017-02-25 12:31 UTC, zburgermeiszter commented on docker-compose.yml
> +      RSA_PRIVATE_KEY: |
This is just an example for people who want to use `docker-compose`. It's not a best practice to commit secret things to a git repo. That's why I removed the middle of them.

2017-02-25 12:50 UTC, zburgermeiszter commented on index.js
> -    res.locals.apiVersion = req.params.version
It was an unnecessary variable declaration as it has been used only at  [process.js:27](https://github.com/eduardoboucas/staticman/blob/46652bd6417eb41082590c8de0abdec5d2edaa79/controllers/process.js#L27).
Therefore I updated the usage point at the PR [process.js:61](https://github.com/zburgermeiszter/staticman/blob/356f3a692a0ddd630e87ce548d6f136307b245b3/controllers/process.js#L61)

2017-02-25 15:21 UTC, eduardoboucas commented
(I've updated `dev` and changed back the base of the PR)

2017-02-25 16:19 UTC, zburgermeiszter commented
> How would people (end users) install this? Do they need to create an account with a third-party? If so, which one?
If they want reCAPTCHA support to their website, they have to create API key(s) on it's [website](https://www.google.com/recaptcha/intro/index.html).
I also moved the enabler flag to SiteConfig. So, from now on people can configure reCAPTCHA enforcement straight form their repo. Needs to be added to the sample config or documentation.

2017-02-25 16:37 UTC, zburgermeiszter commented
> What code do they need to include in their forms for this to work?

They need to add the reCAPTCHA script to their page
`<script src='https://www.google.com/recaptcha/api.js'></script>`

Also add the following code to the comment form:
```
<input type="text" name="options[reCAPTCHA][siteKey]" value="6Lf7-gk...4Ov">
<input type="text" name="options[reCAPTCHA][encryptedSecret]" value="XbSgEcI...DUQ==">
<div class="g-recaptcha" data-sitekey="6Lf7-gkUAA...WiyiQ"></div>
```

A full example form:
```
<form method="post" action="http://localhost:8080/v2/entry/zburgermeiszter/staticman-test/master/comments">
<input type="text" name="fields[name]" value="John Smith">
<input type="text" name="fields[email]" value="user@example.com">
<input type="text" name="fields[message]" value="Hello world">
<input type="text" name="options[slug]" value="this-is-another-slug">
<input type="text" name="options[reCAPTCHA][siteKey]" value="6Lf7-gk...4Ov">
<input type="text" name="options[reCAPTCHA][encryptedSecret]" value="XbSgEcI...DUQ==">

<div class="g-recaptcha" data-sitekey="6Lf7-gkUAA...WiyiQ"></div>

<input type="submit" />
</form>
```

2017-02-25 16:46 UTC, zburgermeiszter commented
> Could you briefly describe the flow of data using reCAPTCHA and how it differs from the current implementation? (e.g. data goes through this function, which makes a request to X, which writes result to Y)

The comment form now contains 2 new fields and 1 extra field is inserted by reCAPTCHA when the user pass the CAPTCHA.

The browser submit the following fields:
`options[reCAPTCHA][siteKey]`
 `options[reCAPTCHA][encryptedSecret]`
`g-recaptcha-response`

On the server side, Staticman decrypts the `encryptedSecret`, instantiates a reCAPTCHA object using the `siteKey` and the decrypted secret, then forward the whole request to the reCAPTCHA API which then validates the `g-recaptcha-response` field against the API credentials.

If the CAPTCHA validation passed, then Staticman continues to the original message processing code.
Also, if the reCAPTCHA is disabled in the SiteConfig, it simply skip the validation and jump straight to the original message processing code.

2017-02-25 16:48 UTC, zburgermeiszter commented
> Are there any breaking changes?

I'm not aware of any, as the reCAPTCHA is not obligatory for Staticman API users, and is disabled by default.
But might worth to set up a test environment for people who want to test it.

2017-02-25 16:50 UTC, eduardoboucas commented
Thanks for your comments, @zburgermeiszter!

Yeah, it's quite a big change, so I want to make sure we get this right. I've set the `dev` branch to automatically deploy to `dev.staticman.net`, so once we're happy with this PR we can merge it and spend some time testing it on the dev instance before merging to `master`.

2017-02-25 19:56 UTC, zburgermeiszter commented
That sounds great.
Please let people know on the [issue](https://github.com/eduardoboucas/staticman/issues/20) page when it's been deployed.

2017-02-25 20:06 UTC, zburgermeiszter commented
I cleaned up the initial PR message to make the fact unambiguous that the CAPTCHA feature is entirely configured in the SiteConfig, no need or dependency on the server config.

2017-02-26 23:46 UTC, eduardoboucas requested changes

2017-02-26 23:46 UTC, eduardoboucas commented on controllers/process.js
> +          req.body.options.reCAPTCHA.encryptedSecret === undefined
Could we replace this with:

```js
if (!req.body.options.reCAPTCHA || !req.body.options.reCAPTCHA.siteKey || !req.body.options.reCAPTCHA.encryptedSecret) {}
```

It makes the expression nicer to the eye and also checks against other falsy values.

2017-02-26 23:46 UTC, eduardoboucas commented on controllers/process.js
> +          return (!err) ? resolve() : reject(err)
For consistency with the rest of the codebase, would you mind replacing with:

```js
if (err) {
  return reject(err)
}

return resolve()
```

2017-02-26 23:46 UTC, eduardoboucas commented on docker-compose.yml
> +      RSA_PRIVATE_KEY: |
Sure, I just think it's a bit confusing to leave partially filled in tokens and keys. I'd rather make it more obvious that it is a placeholder that needs replacing, something like `GITHUB_TOKEN: YOUR-TOKEN-HERE`.

Does that make sense?

2017-02-26 23:46 UTC, eduardoboucas commented on controllers/process.js
> +    staticman
When chaining functions across multiple lines, I'd rather see the first one in the same line as the object being called on. So:

```js
staticman.getSiteConfig()
  .then()
  .catch()
```

Would you mind changing that?

2017-02-26 23:46 UTC, eduardoboucas commented on lib/Staticman.js
> +    this
When chaining functions across multiple lines, I'd rather see the first one in the same line as the object being called on. So:

```js
staticman.getSiteConfig()
  .then()
  .catch()
```

Would you mind changing that?

2017-02-26 23:46 UTC, eduardoboucas commented on controllers/process.js
> +        recaptcha.init(
Sorry for being picky, but I'm not a fan of having function calls across multiple lines. If it gets too long for a single line, could you create variables with the arguments and use them in the function call instead?

2017-02-26 23:46 UTC, eduardoboucas commented on siteConfig.js
> +      default: true
Do we really want to make it `true` by default? Doesn't this mean a breaking change, because suddenly sites will fail unless reCaptcha is provided?

2017-02-27 00:20 UTC, zburgermeiszter commented on siteConfig.js
> +      default: true
Already fixed it, but forget to push the commit. I'll push it with the other fixes.

2017-02-27 08:14 UTC, zburgermeiszter commented
I updated the form example in an earlier comment. The last div was a mistake in it.

2017-02-27 21:14 UTC, zburgermeiszter commented
I have done the requested changes.

2017-02-27 23:27 UTC, zburgermeiszter commented
ReCaptcha credentials are now verified against the Site Config in the Source branch in order to prevent spoofing them with a different API credentials set to a weaker security level.

2017-02-28 15:17 UTC, eduardoboucas commented
Thanks @zburgermeiszter, much appreciated! Will look into this soon and deploy to the `dev` instance.

2017-03-02 20:41 UTC, merged